#!/usr/bin/env sh

notify-send "XMonad" "Building XMonad"

# tangle the org file -- `ntangle` is much faster than the elisp implementation
# see [[https://github.com/OrgTangle/ntangle]]
ntangle src/config.org

stack build
status=$?

if [[ $status -ne 0 ]]; then
    notify-send --urgency=critical "XMonad" "Building failed!"
    exit $status
else
    notify-send "XMonad" "Build successful"
fi
